### ISSUE TITLE
Proceed to Cart Button stuck in loop

### ISSUE THREAD

**Issue by csims723** [woothemes/boutique#23] opened 2015-10-21 03:57 UTC
I am using Boutique as a child theme for Storefront and the Proceed to check out button is stuck in a loop back to the shopping cart. Any assistance would be helpful as I am losing customers.

**Comment by csims723** [comment] 2015-10-21 03:58
See more at www.advancedtrap.com

**Comment by jameskoster** [comment] 2015-10-23 17:07
I think this is an issue with how your site is set up. The button points to http://trappintales.com/AT/checkout/ and visiting that URL directly works just fine. I notice that as I browse around your site, the URL in the address bar never changes though. Not sure if that's intentional or not but it's not very useful and is probably related to this.

Certainly not a bug in the theme, so I'll close this issue.

**Closed by jameskoster** 2015-10-23 17:07 UTC

**Comment by csims723** [comment] 2015-10-23 17:17
Jameskoster. 
The site is set up with the URL as a masking redirect. I continue to get an error on the woocommerce report that there is a 1.5 update on the theme. I have not been able to find this update. I really need a solution to this issue can you help at all?

**Comment by jameskoster** [comment] 2015-10-23 17:28
Maybe check that all your pages are set up correctly and that you only have one checkout page.

Try disabling the URL mask too. It's probably related to that.

Beyond that, you'll need to look at your server logs to pinpoint the issue.

**Comment by csims723** [comment] 2015-10-23 20:09
Thanks for the tips Ill begin there

**Comment by csims723** [comment] 2015-10-24 00:45
Jameskoster,
I think the URL forward with masking was the issue. I turned off the masking and the shopping cart button began working like a champ. Thanks for taking the time to offer suggestions instead of just giving up on it. Thanks again
